---
- block:
  - name: Discover the latest version
    delegate_to: localhost
    shell: |-
      # api.github.com has no ipv6 in 2023.. try to use git with googlesource first
      {
        if command -v git >&- 2>&-; then
          git ls-remote --tags --sort='v:refname' https://go.googlesource.com/go "refs/tags/go*" | sed -nE 's#^.*refs/tags/go([0-9.]+)$#\1#p'
        elif command -v curl >&- 2>&-; then
          curl https://api.github.com/repos/golang/go/git/refs/tags/ | sed -nE 's#^.*"refs/tags/go([0-9.]+)".*$#\1#p' | sort -V
        fi
      } | tail -n 1
    register: latest_release
    check_mode: no
    changed_when: False

  - name: Setting version from latest release
    set_fact:
      go_version: "{{ latest_release.stdout_lines[0] }}"
  when:
    - go_version is not defined

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  check_mode: no
  ignore_errors: yes
  register: current_go_version
  changed_when: false

- name: Install Go
  include_tasks: install_go.yml
  when: current_go_version is failed or current_go_version.stdout != go_version_target

- name: Add the Go bin directory to the PATH environment variable for all users
  become: yes
  copy:
    src: go-bin.sh
    dest: /etc/profile.d

- name: Set GOPATH for all users
  become: yes
  copy:
    src: go-path.sh
    dest: /etc/profile.d
  when: set_go_path|bool # TODO ugly, see https://github.com/ansible/ansible/issues/53428#issuecomment-495175232
